In [4]:
import torch
data=[[1,2],[3,4]]

In [5]:
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [6]:
tensor = x_data

In [7]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [8]:
tensor[:,1]=0
print(tensor)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

tensor([[1, 0],
        [3, 0]])
tensor([[1, 3],
        [3, 9]])
tensor([[1, 3],
        [3, 9]])
